#ifndef GAMEPAD_KEYS_H
#define GAMEPAD_KEYS_H

#define KEY_PORT1_BTN4 KEY_ENTER
#define KEY_PORT1_BTN3 KEY_RSHIFT
#define KEY_PORT1_BTN2 KEY_ALTGR
#define KEY_PORT1_BTN1 KEY_RCTRL

#define KEY_PORT1_LEFT KEY_LEFTARROW
#define KEY_PORT1_RIGHT KEY_RIGHTARROW
#define KEY_PORT1_UP KEY_UPARROW
#define KEY_PORT1_DOWN KEY_DOWNARROW

#define KEY_PORT2_BTN4 KEY_CAPSLOCK
#define KEY_PORT2_BTN3 KEY_LSHIFT
#define KEY_PORT2_BTN2 KEY_LCTRL
#define KEY_PORT2_BTN1 KEY_ALT

#define KEY_PORT2_LEFT KEY_A
#define KEY_PORT2_RIGHT KEY_D
#define KEY_PORT2_UP KEY_W
#define KEY_PORT2_DOWN KEY_S

#endif

